<h1 align='center'> Numpy Basics </h1>

In [1]:
import numpy as np 

<h3>1. Create a NumPy array with values ranging from 0 to 9.</h3>

In [9]:
#Approach 1
np_array=np.array([i for i in range(0,10)])
display(f'Numpy Array Approach 1: {np_array}')
#Approach 2
np_array=np.arange(10)
display(f'Numpy Array Approach 2: {np_array}')

'Numpy Array Approach 1: [0 1 2 3 4 5 6 7 8 9]'

'Numpy Array Approach 2: [0 1 2 3 4 5 6 7 8 9]'

<h3>2. Create a 3x3 Matrix, Also create 3x3 matrix with all Trues </h3>

In [18]:
matrix_33=np.array([[1,2,3],[4,5,6],[7,8,9]])
display(np.shape(matrix_33))
display(matrix_33)

#Approach 1
trues=[True,True,True]
matrix_33=np.array([trues,trues,trues])
display(f'Approach 1:')
display(matrix_33)
#Approach 2
matrix_33=np.full((3,3),True,dtype=bool)
display('Approach 2: ')
display(matrix_33)


(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

'Approach 1:'

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

'Approach 2: '

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<h3>3. Extract all odd numbers from the array 'arr' which consists value from 1 to 10</h3>

In [21]:
arr=np.arange(10)
odd_arr=arr[arr%2!=0]
display(odd_arr)

array([1, 3, 5, 7, 9])

<h3>4. Replace all odd numbers in the array arr with -1.</h3>

In [25]:
arr=np.arange(10)
arr[arr%2!=0]=-1
display(arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

<h3>4.Convert a 1D array to a 2D array with 2 rows. </h3>

In [38]:
arr=np.arange(10)
display(arr)
arr=arr.reshape(2,-1) #Rows,Columns
display(arr)
display(arr.reshape(-1))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3>5. Stack two arrays vertically.</h3>

In [45]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
arr_vstack = np.vstack((arr1, arr2))
display(arr_vstack)

arr_3=np.arange(10)
arr_4=np.arange(10)
display(np.vstack((arr_3,arr_4)))

display(np.hstack((arr_3,arr_4)))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3>6. Create Random array of 10 elements with random elements </h3>

In [61]:
arr=(np.random.rand(10)*10).astype(int)
display(arr)

array([4, 4, 4, 0, 7, 2, 8, 7, 1, 3])

<h4>6. Get the common elements of 2 arrays </h4>

In [62]:
arr_1=(np.random.rand(10)*10).astype(int)
arr_2=(np.random.rand(10)*10).astype(int)
display(arr_1)
display(arr_2)
np.intersect1d(arr_1,arr_2)

array([9, 5, 3, 8, 8, 3, 3, 8, 7, 5])

array([1, 1, 7, 4, 1, 8, 4, 6, 8, 6])

array([7, 8])

<h3>7. Sort array a. </h3>

In [74]:
arr=(np.random.rand(10)*30).astype('int')
display(f'Original array: {arr}')
display(f'Sorted array Assending: {np.sort(arr)}')
display(f'Sorted array Decending: {np.sort(arr)[::-1]}')

'Original array: [27  0 19 26 17  6 23 19 27 25]'

'Sorted array Assending: [ 0  6 17 19 19 23 25 26 27 27]'

'Sorted array Decending: [27 27 26 25 23 19 19 17  6  0]'

<h3>8. Transpose of a Matrix </h3>

In [82]:
arr_1=((np.random.rand(4)*20).astype(int)).reshape(-1,2)
display('Original Matrix:')
display(arr_1)
display(f'Transposed Matrix: {arr_1.T}')

'Original Matrix: [[9 8]\n [1 9]]'

'Transposed Matrix: [[9 1]\n [8 9]]'